### ISSUE TITLE
I am using SSL certificate But still hackers are able to hack the openAI key

### ISSUE THREAD

**Issue by ankushdhawan** [FuturraGroup/OpenAI#13]

**Comment by kyrylo-mukha** [comment]
Hi.
How did you investigate it? Have you tried the MITM attack yourself or how did you know "it doesn't work"?
How do you pass your API key to an application? If it's Google Remote Config or something like that, it's transmitting data in an open way and the key can be stolen.
How are we supposed to figure out exactly what the problem is from one sentence with no information? Use the magic 8 ball?
This is an open source project. If you have problems - provide a detailed explanation so that we can understand how it is reproduced for you, or what this problem refers to.

**Comment by ankushdhawan** [comment]
Hi,

My openAI key has been hacked by hackers when i make it live on appstore. So for implementing SSL i follow these steps

How to use SSL Handshake:

Get SSL Certificate from OpenAI
Open https://api.openai.com/ from Safari. It's necessary to open and save from Safari because it saves certificate in binary format.
Press on lock icon in address bar
On showed popup press Show Certificate
Select botom one certificate in list and Drag-n-Drop certificate icon anywhare you need to save.

2. Add certificate to your project 3. Initialize our library providing path to this file
Example with Bundle source path:

var openAI: OpenAIKit?

if let filePath = Bundle.main.path(forResource: "MyCert", ofType: "cer") {
	openAI = OpenAIKit(apiToken: apiToken, organization: nil, sslCerificatePath: filePath)
}

I stored Mycert.cer in my project . Can you please guide what should i do extra for protecting my openAI key from hackers

**Comment by kyrylo-mukha** [comment]
SSL Handshake is protection from MITM attack when someone replaces real SSL certificate with corrupted and can decrypt your data (like Charles works).

Can you provide link for your app?

Recomendations to protect:
1) Keep actual version of OpenAI cetrificate in app. You can download it every launch from your server that makes copy of OpenAI certificate (binary format only, nota base64).
2) Make sure that your certificate file actually exists in the specified path. Otherwise, if this path is incorrect, everything will work as a default URLRequest without checking the certificate.
3) Don't get your key from API or remote configs in not encrypted format. For example encypt the key on your server and localy in app store keys to decrypt, get encrypted key from your API and decrypt on device.

**Comment by ankushdhawan** [comment]
The link of the app : https://apps.apple.com/us/app/chat-ai-assistant-watch-chat/id6477316422

1 Keep actual version of OpenAI cetrificate in app. You can download it every launch from your server that makes copy of OpenAI certificate (binary format only, nota base64). you means i need to store openAI certificate in my server and download it from server. which is making my app slow as i need to download it every time

One mistake i found that in my logs that i print my openAi token in logs. is it the actual reason that hackers are able to hack my openAi key

**Comment by kyrylo-mukha** [comment]
You implemended the integration of SSL Handshake in wrong way. I've downloaded your app and requests sends in open way without SSL validation. I see the key in headears. This means that how suggested in step 2 - you've provided wrong/incorrect path to file and library can't handle it.
To test SSL Handshake install Charles on your Mac, setup the proxy on your iPhone and it will fake SSL certificate to decode your data. When you started to see that requests to OpenAI is empty - you did all right. Also if you using SPM you can set breakpoints in `OpenAISSLDelegate.swift` in our library to actualy see on what step your certificate validation goes wrong and falls down to default logic.

**Comment by ankushdhawan** [comment]
i think cert path is correct you can see in this  screenshot it is passing all certificate validation . please check the image in break point i put
<img width="1052" alt="Screenshot 2024-04-18 at 8 08 15 PM" src="https://github.com/FuturraGroup/OpenAI/assets/7744139/4bc17c5f-ced4-40bf-af0f-cfb70efd65d6">

**Comment by kyrylo-mukha** [comment]
Check out validation breakpoints with connected Charles proxy to catch packages. In our production certificate validation restricts request with connected Charles. In your app I see everything.

**Comment by kyrylo-mukha** [comment]
Did you tried out debug with connected Charles?

**Comment by ankushdhawan** [comment]
Yes I think my issue get resolved. Thank you for your support without your support i am not able to resolve this issue

**Comment by kyrylo-mukha** [comment]
You are welcome. We were happy to help resolve the issue.
