### ISSUE TITLE
My SSl certificate got expired within month. is there any way in which i can set expireation ssl certificate

### ISSUE THREAD

**Issue by ankushdhawan** [FuturraGroup/OpenAI#15]
i used below steps to download the SSL certificate

Get SSL Certificate from OpenAI
Open https://api.openai.com/ from Safari. It's necessary to open and save from Safari because it saves certificate in binary format.
Press on lock icon in address bar
On showed popup press Show Certificate
Select botom one certificate in list and Drag-n-Drop certificate icon anywhare you need to save.

**Comment by kyrylo-mukha** [comment]
Hello. Please read the carefully description before the SSL Handshake tutorial. It states the following:

**Attention! We _DON'T SAVE_ any certificates and _DOESN'T MANAGE_ them!
We use the data from the provided `*.cer` file _ONLY_ for comparison with the server certificate.
We are _not responsible_ for the relevance and integrity of the provided certificate.**

**These actions are within the competence of our library, and you yourself must monitor the validity of the certificate, be responsible for downloading new versions, etc.**

This means that we do not update this file in any way, since we have no guarantees that it has not been replaced, we do not control its relevance.
You can maintain the relevance of this file yourself - by regular updates, downloading from your own server, etc.
You can implement an algorithm on your server that will regularly update this file itself, **BUT BE CAREFUL(!)** the certificate **MUST** be in **_binary_** format, **not** base64. Also note that it should be the lowest level certificate, not a root certificate.
